// Package s3upload provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package s3upload

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// AbortUploadBody defines model for AbortUploadBody.
type AbortUploadBody struct {
	ObjectName string `json:"ObjectName"`
	UploadID   string `json:"UploadID"`
}

// AbortUploadResp defines model for AbortUploadResp.
type AbortUploadResp struct {
	Message    string `json:"Message"`
	ObjectName string `json:"ObjectName"`
	UploadID   string `json:"UploadID"`
}

// CompletePart defines model for CompletePart.
type CompletePart struct {
	ChecksumSHA256 string `json:"ChecksumSHA256"`
	ETag           string `json:"ETag"`
	PartNumber     int    `json:"PartNumber"`
}

// CompleteUploadBody defines model for CompleteUploadBody.
type CompleteUploadBody struct {
	ChecksumSHA256 string         `json:"ChecksumSHA256"`
	ObjectName     string         `json:"ObjectName"`
	Parts          []CompletePart `json:"Parts"`
	UploadID       string         `json:"UploadID"`
}

// CompleteUploadResp defines model for CompleteUploadResp.
type CompleteUploadResp struct {
	Key      string `json:"Key"`
	Location string `json:"Location"`
}

// HTTPValidationError defines model for HTTPValidationError.
type HTTPValidationError struct {
	Detail *[]ValidationError `json:"detail,omitempty"`
}

// InternalError defines model for InternalError.
type InternalError struct {
	// Code A specific error code indicating the error type
	Code string `json:"code"`

	// Details Additional context or information about the error
	Details *string `json:"details,omitempty"`

	// Message A human-readable message providing more details about the error
	Message string `json:"message"`

	// Timestamp The time when the error occurred
	Timestamp *time.Time `json:"timestamp,omitempty"`
}

// PresignedUrlBody defines model for PresignedUrlBody.
type PresignedUrlBody struct {
	ObjectName string `json:"ObjectName"`
	Parts      int    `json:"Parts"`
}

// PresignedUrlResp defines model for PresignedUrlResp.
type PresignedUrlResp struct {
	UploadID string   `json:"UploadID"`
	Urls     []string `json:"Urls"`
}

// ValidationError defines model for ValidationError.
type ValidationError struct {
	Loc  []ValidationErrorLocInner `json:"loc"`
	Msg  string                    `json:"msg"`
	Type string                    `json:"type"`
}

// ValidationErrorLocInner defines model for ValidationError_loc_inner.
type ValidationErrorLocInner struct {
	union json.RawMessage
}

// ValidationErrorLocInner0 defines model for .
type ValidationErrorLocInner0 = string

// ValidationErrorLocInner1 defines model for .
type ValidationErrorLocInner1 = int

// AbortMultipartUploadJSONRequestBody defines body for AbortMultipartUpload for application/json ContentType.
type AbortMultipartUploadJSONRequestBody = AbortUploadBody

// CompleteUploadJSONRequestBody defines body for CompleteUpload for application/json ContentType.
type CompleteUploadJSONRequestBody = CompleteUploadBody

// GetPresignedUrlsJSONRequestBody defines body for GetPresignedUrls for application/json ContentType.
type GetPresignedUrlsJSONRequestBody = PresignedUrlBody

// AsValidationErrorLocInner0 returns the union data inside the ValidationErrorLocInner as a ValidationErrorLocInner0
func (t ValidationErrorLocInner) AsValidationErrorLocInner0() (ValidationErrorLocInner0, error) {
	var body ValidationErrorLocInner0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationErrorLocInner0 overwrites any union data inside the ValidationErrorLocInner as the provided ValidationErrorLocInner0
func (t *ValidationErrorLocInner) FromValidationErrorLocInner0(v ValidationErrorLocInner0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationErrorLocInner0 performs a merge with any union data inside the ValidationErrorLocInner, using the provided ValidationErrorLocInner0
func (t *ValidationErrorLocInner) MergeValidationErrorLocInner0(v ValidationErrorLocInner0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsValidationErrorLocInner1 returns the union data inside the ValidationErrorLocInner as a ValidationErrorLocInner1
func (t ValidationErrorLocInner) AsValidationErrorLocInner1() (ValidationErrorLocInner1, error) {
	var body ValidationErrorLocInner1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationErrorLocInner1 overwrites any union data inside the ValidationErrorLocInner as the provided ValidationErrorLocInner1
func (t *ValidationErrorLocInner) FromValidationErrorLocInner1(v ValidationErrorLocInner1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationErrorLocInner1 performs a merge with any union data inside the ValidationErrorLocInner, using the provided ValidationErrorLocInner1
func (t *ValidationErrorLocInner) MergeValidationErrorLocInner1(v ValidationErrorLocInner1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ValidationErrorLocInner) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ValidationErrorLocInner) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// AbortMultipartUploadWithBody request with any body
	AbortMultipartUploadWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	AbortMultipartUpload(ctx context.Context, body AbortMultipartUploadJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CompleteUploadWithBody request with any body
	CompleteUploadWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CompleteUpload(ctx context.Context, body CompleteUploadJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetPresignedUrlsWithBody request with any body
	GetPresignedUrlsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	GetPresignedUrls(ctx context.Context, body GetPresignedUrlsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) AbortMultipartUploadWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAbortMultipartUploadRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AbortMultipartUpload(ctx context.Context, body AbortMultipartUploadJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAbortMultipartUploadRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CompleteUploadWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCompleteUploadRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CompleteUpload(ctx context.Context, body CompleteUploadJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCompleteUploadRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetPresignedUrlsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetPresignedUrlsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetPresignedUrls(ctx context.Context, body GetPresignedUrlsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetPresignedUrlsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewAbortMultipartUploadRequest calls the generic AbortMultipartUpload builder with application/json body
func NewAbortMultipartUploadRequest(server string, body AbortMultipartUploadJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewAbortMultipartUploadRequestWithBody(server, "application/json", bodyReader)
}

// NewAbortMultipartUploadRequestWithBody generates requests for AbortMultipartUpload with any type of body
func NewAbortMultipartUploadRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/s3/abortMultipartUpload")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewCompleteUploadRequest calls the generic CompleteUpload builder with application/json body
func NewCompleteUploadRequest(server string, body CompleteUploadJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCompleteUploadRequestWithBody(server, "application/json", bodyReader)
}

// NewCompleteUploadRequestWithBody generates requests for CompleteUpload with any type of body
func NewCompleteUploadRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/s3/completeUpload")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetPresignedUrlsRequest calls the generic GetPresignedUrls builder with application/json body
func NewGetPresignedUrlsRequest(server string, body GetPresignedUrlsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewGetPresignedUrlsRequestWithBody(server, "application/json", bodyReader)
}

// NewGetPresignedUrlsRequestWithBody generates requests for GetPresignedUrls with any type of body
func NewGetPresignedUrlsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/s3/presignedUrls")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// AbortMultipartUploadWithBodyWithResponse request with any body
	AbortMultipartUploadWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AbortMultipartUploadResponse, error)

	AbortMultipartUploadWithResponse(ctx context.Context, body AbortMultipartUploadJSONRequestBody, reqEditors ...RequestEditorFn) (*AbortMultipartUploadResponse, error)

	// CompleteUploadWithBodyWithResponse request with any body
	CompleteUploadWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CompleteUploadResponse, error)

	CompleteUploadWithResponse(ctx context.Context, body CompleteUploadJSONRequestBody, reqEditors ...RequestEditorFn) (*CompleteUploadResponse, error)

	// GetPresignedUrlsWithBodyWithResponse request with any body
	GetPresignedUrlsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*GetPresignedUrlsResponse, error)

	GetPresignedUrlsWithResponse(ctx context.Context, body GetPresignedUrlsJSONRequestBody, reqEditors ...RequestEditorFn) (*GetPresignedUrlsResponse, error)
}

type AbortMultipartUploadResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *AbortUploadResp
	JSON422      *HTTPValidationError
	JSON500      *InternalError
}

// Status returns HTTPResponse.Status
func (r AbortMultipartUploadResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AbortMultipartUploadResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CompleteUploadResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CompleteUploadResp
	JSON422      *HTTPValidationError
	JSON500      *InternalError
}

// Status returns HTTPResponse.Status
func (r CompleteUploadResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CompleteUploadResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetPresignedUrlsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PresignedUrlResp
	JSON422      *HTTPValidationError
	JSON500      *InternalError
}

// Status returns HTTPResponse.Status
func (r GetPresignedUrlsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetPresignedUrlsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// AbortMultipartUploadWithBodyWithResponse request with arbitrary body returning *AbortMultipartUploadResponse
func (c *ClientWithResponses) AbortMultipartUploadWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AbortMultipartUploadResponse, error) {
	rsp, err := c.AbortMultipartUploadWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAbortMultipartUploadResponse(rsp)
}

func (c *ClientWithResponses) AbortMultipartUploadWithResponse(ctx context.Context, body AbortMultipartUploadJSONRequestBody, reqEditors ...RequestEditorFn) (*AbortMultipartUploadResponse, error) {
	rsp, err := c.AbortMultipartUpload(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAbortMultipartUploadResponse(rsp)
}

// CompleteUploadWithBodyWithResponse request with arbitrary body returning *CompleteUploadResponse
func (c *ClientWithResponses) CompleteUploadWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CompleteUploadResponse, error) {
	rsp, err := c.CompleteUploadWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCompleteUploadResponse(rsp)
}

func (c *ClientWithResponses) CompleteUploadWithResponse(ctx context.Context, body CompleteUploadJSONRequestBody, reqEditors ...RequestEditorFn) (*CompleteUploadResponse, error) {
	rsp, err := c.CompleteUpload(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCompleteUploadResponse(rsp)
}

// GetPresignedUrlsWithBodyWithResponse request with arbitrary body returning *GetPresignedUrlsResponse
func (c *ClientWithResponses) GetPresignedUrlsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*GetPresignedUrlsResponse, error) {
	rsp, err := c.GetPresignedUrlsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetPresignedUrlsResponse(rsp)
}

func (c *ClientWithResponses) GetPresignedUrlsWithResponse(ctx context.Context, body GetPresignedUrlsJSONRequestBody, reqEditors ...RequestEditorFn) (*GetPresignedUrlsResponse, error) {
	rsp, err := c.GetPresignedUrls(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetPresignedUrlsResponse(rsp)
}

// ParseAbortMultipartUploadResponse parses an HTTP response from a AbortMultipartUploadWithResponse call
func ParseAbortMultipartUploadResponse(rsp *http.Response) (*AbortMultipartUploadResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AbortMultipartUploadResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AbortUploadResp
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseCompleteUploadResponse parses an HTTP response from a CompleteUploadWithResponse call
func ParseCompleteUploadResponse(rsp *http.Response) (*CompleteUploadResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CompleteUploadResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CompleteUploadResp
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetPresignedUrlsResponse parses an HTTP response from a GetPresignedUrlsWithResponse call
func ParseGetPresignedUrlsResponse(rsp *http.Response) (*GetPresignedUrlsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetPresignedUrlsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PresignedUrlResp
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xYTXPbNhP+Kxi875GJFLvpgTc39cSeNonHlnuox5OByZWIhARQALSj0ei/dxbgB0SC",
	"sRNZmR5ysUhwsR/PPrtYeEMzWSkpQFhD0w01WQEVc48nd1Lba1VKlv8m8zUuwRdWqRLw8cPdJ8jse1YB",
	"TcOXhPot57/TtH/cJlRpqUBbDma4fUMtt2WvR3g9dq1wzVjNxQo19Ir7HX6N52P5bUI1/FNzDTlNbyZc",
	"vE06TcNwt0m4dAlGDRB4B8awFW69qrMMIAf0Yk9cOqV9iO1SBJH/CIpJ52McTwfeNqFvJGJn4YJpOwDz",
	"TQHZZ1NXV2cnR69/pelwIaGnC7aiqf9JKKp4X1d3oGk6H6E41NZH2n4xBfNqR/h4O/2OU+sMjuRCD3pp",
	"XBV+tdvDhYUV6BGY8RB3NAd47oAXgDlZoY9DOs1VNGJoerN3YvZVcPvEutkn499TRQ1AG8otVO7h/xqW",
	"NKX/m/UNddZ009kwdyFbTK+eac3We9fo19KcdCZjLTBCqRHRIo3wD1gP+fOnzJjlUtCUFtaqdDaruOBy",
	"Jp3QOH1ORR8rvkZA77X2ot3aY7AEgqh+Muy2WZ0tFhd/sZLnbtep1lIP4s7BMl66KillhjYG8h9LmX3k",
	"QrhmMP3tNqGVwQrAv10Y7gcL6GC6b0dpaCN6Iq2H8ATMbjQNqR1IxPDdJvRcWNCClR3gux5mMm+wN5nm",
	"quHYCTEKMr7kGQHcR1CMcJFzzLlYEVtA88X5E+GWd9hEdOc5x0dWkkwKC18skZpwsZS6cq4Tdidr25uI",
	"aa/6Y33oeVFXTLzQwHJ2VwJpJInS8p7n6HslNZDGvafYsrwCY1mlxtYWBRD8TB4KEAEoMstqrd384sPC",
	"DDILL1D40cpyOeljvO3k+2q/0GD4SkB+rctvGiabPjt/lgGya9rYjKq6oumryV48dWhHvAtaySjOQeyR",
	"7hk73hJ6rZGLN/63eR3X67edE63WoLoj5Gm0eLuj6g2hGLo7gUPbUL/eTA/XQQeYOUPf1+ACiwFUqHB8",
	"hDt/njTE+4Vg4HQluYj2qUEGvOkg6CAFkd46HU66oUysPyzdYTb0cDOqiWkzIUToLfbJcR+6PL1akJOL",
	"cwIiV5IL27Q70GQpNVEte8jVMakdywgTOWE6K/g99sQHqT8vS/lAMFN5XaKjvU+ni7O/yYkTBk2uQN/z",
	"DMG8B228A/OXr17OERKpQDDFaUqP3VJCFbOFI8bMHM8YXmLe1aXlirW3GXcoSeNuMEgsF/x53l55htI+",
	"Y2Bs2/fcKSLcdqZUyf1YMvtk/GDjufcYM0e31V1qWF2DWzBKCuOJfzSfH8K8L++tO0LDHLtLsTHLuiSX",
	"jRsI+C9HR8/mRXSEGHvSi5CuFF4/Ixi7I0vEgVbAURF068U2oaauKqbXLXdIRx7SsceylTsJVNBS8SzY",
	"Jo6h2c7wOs3N3SH3QKyMXSB+LDFjs/xPbu7JzRbUJ5Nyd3mSk2/BXuxIHoaV46Hsx3JyPAz9ZOSejHwL",
	"lnSwknZYnSIlbnW6/L+0al3SlM7wAvxvAAAA//96UdSp/xYAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
